/*******************************************************************************
 *
 * MIT License
 *
 * Copyright 2026 AMD ROCm(TM) Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *******************************************************************************/

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "origami/types.hpp"

namespace origami {

// ============================================================================
//  GEMM Categorization for ML Kernel Recommender Training
// ============================================================================
//
//  Purpose: partition the GEMM (M, N, K) space into categories such that:
//    1. Each category has distinct characteristics that separate it from others
//    2. Within each category, a per-category ML recommender can learn which
//       MT×MI kernel wins
//    3. The categories cover the entire GEMM space
//    4. Training data can be generated by sampling within each category
//
//  125 categories: 5(M) × 5(N) × 5(K), all in geometric 4x progression.
//
//  M/N boundaries: {64, 256, 1024, 4096}  — log2: {6, 8, 10, 12}
//  K boundaries:   {128, 512, 2048, 8192} — log2: {7, 9, 11, 13}
//
//  Derivation:
//    - TensileLite Ratio distance = |log(M1/M2)|+|log(N1/N2)|+|log(K1/K2)|
//      → uniform log2-spacing gives equal-width bins in matching metric
//    - Origami latency model: tile-occupancy transitions at M/MT_max ∈ {1,4,16}
//    - GridBased K grid points validated: each range captures ~3 grid points
//
// ============================================================================

/**
 * @brief Size range for M and N (output tile grid dimensions).
 */
enum class mn_range_t : std::uint8_t {
  tiny   = 0,  ///< [1, 64]
  small  = 1,  ///< [65, 256]
  medium = 2,  ///< [257, 1024]
  large  = 3,  ///< [1025, 4096]
  xlarge = 4,  ///< [4097, inf)

  count  = 5
};

/**
 * @brief Size range for K (reduction loop depth).
 */
enum class k_range_t : std::uint8_t {
  tiny   = 0,  ///< [1, 128]
  small  = 1,  ///< [129, 512]
  medium = 2,  ///< [513, 2048]
  large  = 3,  ///< [2049, 8192]
  xlarge = 4,  ///< [8193, inf)

  count  = 5
};

// ============================================================================
// Range boundaries
// ============================================================================

inline constexpr std::array<std::size_t, 5> MN_RANGE_UPPER_BOUNDS = {
    64, 256, 1024, 4096, SIZE_MAX};

inline constexpr std::array<std::size_t, 5> K_RANGE_UPPER_BOUNDS = {
    128, 512, 2048, 8192, SIZE_MAX};

inline constexpr std::size_t NUM_GEMM_CATEGORIES =
    static_cast<std::size_t>(mn_range_t::count) *
    static_cast<std::size_t>(mn_range_t::count) *
    static_cast<std::size_t>(k_range_t::count);

// ============================================================================
// Category type
// ============================================================================

/**
 * @brief GEMM category for ML training dataset generation.
 *
 * Each category defines a region in (M, N, K) space where a
 * per-category ML recommender selects among MT×MI kernels.
 *
 * Usage:
 *   1. Iterate all 125 categories
 *   2. For each, call generate_training_samples() to get (M,N,K) points
 *   3. For each point, run origami::rank_configs() to get kernel rankings
 *   4. Train per-category ML model on (features, best_kernel) pairs
 */
struct gemm_category_t {
  mn_range_t m_range;
  mn_range_t n_range;
  k_range_t  k_range;
  bool       batched = false;

  std::size_t id() const noexcept;

  std::size_t m_lower() const noexcept;
  std::size_t m_upper() const noexcept;
  std::size_t n_lower() const noexcept;
  std::size_t n_upper() const noexcept;
  std::size_t k_lower() const noexcept;
  std::size_t k_upper() const noexcept;

  double representative_arithmetic_intensity(double bytes_per_element = 2.0) const noexcept;

  /**
   * @brief Generate log-uniform training samples within this category.
   *
   * Samples are spaced uniformly in log2-space, matching TensileLite's
   * Ratio distance metric.  For the unbounded xlarge ranges, samples
   * extend to cap (default 32768).
   *
   * @param samples_per_dim Number of samples per dimension
   * @param cap Upper cap for unbounded (xlarge) ranges
   * @return Vector of (M, N, K) triples
   */
  std::vector<dim3_t> generate_training_samples(std::size_t samples_per_dim = 4,
                                                std::size_t cap = 32768) const;

  std::string to_string() const;

  bool operator==(const gemm_category_t& o) const noexcept {
    return m_range == o.m_range && n_range == o.n_range &&
           k_range == o.k_range && batched == o.batched;
  }
  bool operator!=(const gemm_category_t& o) const noexcept { return !(*this == o); }
};

// ============================================================================
// ML Feature Vector
// ============================================================================

/**
 * @brief ML features derived from (M, N, K) for kernel recommendation.
 *
 * These features capture the mathematical quantities from origami's
 * latency model that determine which MT×MI kernel wins:
 *
 *   log2_m, log2_n, log2_k:
 *     Raw dimensions in log-space.  TensileLite's Ratio distance
 *     operates on these.
 *
 *   arithmetic_intensity:
 *     AI = 2MNK / ((MK+KN+MN)*bpe).
 *     Determines compute-vs-memory bound regime.
 *     From gemm.cpp: L_tile = max(L_compute, L_mem).
 *
 *   mn_aspect_ratio:
 *     log2(M/N).  Determines whether tall-skinny (M>>N) or
 *     short-wide (N>>M) tiles are preferred.  From origami.cpp
 *     rank_configs tie-breaking: "if M>N, prefer larger MT_M".
 *
 *   k_mn_ratio:
 *     log2(K / sqrt(M*N)).  High values indicate deep reduction
 *     relative to output size — StreamK / split-K may activate.
 *     From gemm.cpp: split_factor = ceil(num_wgs / num_mts).
 *
 *   log2_mn_tiles:
 *     log2(M * N / MT_max^2) where MT_max = 256.
 *     Estimates tile grid size.  From gemm.cpp:
 *     num_timesteps = ceil(num_tiles / N_CU).
 */
struct gemm_ml_features_t {
  double log2_m;
  double log2_n;
  double log2_k;
  double arithmetic_intensity;
  double mn_aspect_ratio;
  double k_mn_ratio;
  double log2_mn_tiles;
};

/**
 * @brief Compute ML features from problem dimensions.
 *
 * @param m M dimension
 * @param n N dimension
 * @param k K dimension
 * @param bytes_per_element bpe for AI calculation (default 2.0 for BF16)
 * @return gemm_ml_features_t Feature vector
 */
gemm_ml_features_t compute_ml_features(std::size_t m, std::size_t n, std::size_t k,
                                       double bytes_per_element = 2.0) noexcept;

// ============================================================================
// Classification functions
// ============================================================================

mn_range_t classify_mn(std::size_t dim) noexcept;
k_range_t classify_k(std::size_t dim) noexcept;

gemm_category_t categorize(const problem_t& problem) noexcept;
gemm_category_t categorize_mnk(std::size_t m, std::size_t n, std::size_t k) noexcept;
gemm_category_t category_from_id(std::size_t id);

double compute_arithmetic_intensity(double m, double n, double k,
                                    double bytes_per_element = 2.0) noexcept;

}  // namespace origami
